### ISSUE TITLE
What is the Data Format in use for the player state?

### ISSUE THREAD

**Issue by sgebr01** [FabioGNR/pyytlounge#1]
Do you know what format is being used for the playback State? It doesn't appear to be JSON(I am unable to parse it, errors continue to occur). How are you handling this to extract relevant information?  Here is an image with the format that I am talking about. 
<img width="2233" alt="Screenshot 2023-01-09 at 11 07 50 PM" src="https://user-images.githubusercontent.com/95095984/211459797-cb30c3a4-9ca6-4d7e-9942-938fd68668b1.png">

Any help is appreciated.
Thank You!

**Comment by FabioGNR** [comment]
Hi, 
I don't know the name but most of the info I got from here: https://github.com/henriquekano/youtube-lounge-api/wiki/Finally-some-api!#events

It's a pattern, you start with a line containing a number that indicates the size of the chunk.
On the next line, the JSON object starts. This continues until the length of all following lines matches the chunk size you read at first line. Once that happens the chunk is considered complete and again a new chunk can be sent (with size+json combo again).
This is the format for POST connect response (not sure if ever more than one chunk).
And also the format for GET bind response, but this is a streaming endpoint so more chunks will arrive with time.

You can check https://github.com/FabioGNR/pyytlounge/blob/75c24ecfa498168d56b09495a3bd351985c71931/src/pyytlounge/wrapper.py#L194 for my implementation of parsing the response.

It's a bit boilerplate because it's async, but you should be able to extract the basic psuedo code from it.
